extends RefCounted

const MOVE_SPEED := 240.0
const GROUND_ACCEL := 1800.0

const COYOTE_TIME := 0.11
const JUMP_BUFFER_TIME := 0.12
const JUMP_VELOCITY := -470.0
const RISE_GRAVITY_MULT := 0.68
const FALL_GRAVITY_MULT := 1.45
const JUMP_CUT_MULT := 0.45

const ATTACK_STARTUP_FRAMES := 3
const ATTACK_ACTIVE_FRAMES := 3
const ATTACK_RECOVERY_FRAMES := 9
const ATTACK_RECOVERY_MOVE_UNLOCK_FRAME := 6

const ATTACK_STARTUP_SPEED_MULT := 0.4
const ATTACK_LUNGE_SPEED := 560.0
const ATTACK_HITBOX_FORWARD_OFFSET := 42.0
const ATTACK_KNOCKBACK_SPEED := 125.0
const ATTACK_SELF_KNOCKBACK_SPEED := 42.0
const ATTACK_HIT_STOP_TIME := 0.04

const PARRY_FRAMES := 8
const HITSTUN_FRAMES := 14
const INVULN_TIME := 0.85
const MAX_HEALTH := 5
